/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demo login — returns role-scoped token */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a citizen request (text or voice) — FR-001/002
         * @description Intake endpoint: runs STT, language detection, classification, NER, geocoding and clustering.
         */
        post: operations["create_request_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload/attach audio for transcription — FR-002
         * @description Accepts citizen audio recording, runs speech transcription and links to citizen request.
         */
        post: operations["upload_audio_requests__request_id__audio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Citizen checks own submission status (reference ID) — FR-005
         * @description Look up submission status by reference code or ID.
         */
        get: operations["get_request_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List clusters, filterable by sector/district/status — FR-071 (analyst+)
         * @description List clusters with multi-factor filtering.
         */
        get: operations["list_clusters_clusters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full cluster detail (analyst+) */
        get: operations["get_cluster_clusters__cluster_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct classification/location — FR-060 (reviewer+) */
        patch: operations["correct_cluster_clusters__cluster_id__patch"];
        trace?: never;
    };
    "/clusters/{cluster_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve/reject/request-more-evidence — FR-059 (reviewer+) */
        post: operations["review_cluster_clusters__cluster_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence panel payload — FR-051 (analyst+) */
        get: operations["get_evidence_clusters__cluster_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/gap-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gap detection result — FR-040–044 (analyst+) */
        get: operations["get_gap_analysis_clusters__cluster_id__gap_analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Priority factor breakdown — FR-050 (analyst+) */
        get: operations["get_priority_clusters__cluster_id__priority_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geospatial/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GeoJSON for map rendering — FR-029 (analyst+)
         * @description Returns valid GeoJSON points for clusters. Unresolved locations have geometry: None (FR-021/033).
         */
        get: operations["cluster_geojson_geospatial_clusters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/infrastructure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Infrastructure/demographic layer query — FR-030/031 (analyst+)
         * @description Returns infrastructure assets and demographic indicators alongside dataset provenance (FR-057).
         */
        get: operations["infrastructure_layer_infrastructure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a policy what-if scenario — FR-053–056 (decision_maker+)
         * @description Executes deterministic scenario planning and returns coverage outcomes.
         */
        post: operations["run_simulation_simulations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Outcome measurement view — FR-064–067 (analyst+)
         * @description Returns baseline vs synthetic followup indicators with correlation disclaimer (FR-067).
         */
        get: operations["get_outcome_clusters__cluster_id__outcome_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dataset registry + versions (admin)
         * @description Lists registered public datasets with versions and source labels (FR-038).
         */
        get: operations["list_datasets_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit trail (admin)
         * @description Returns an immutable audit log trail for governance and review actions (FR-062).
         */
        get: operations["list_audit_logs_audit_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Telegram Bot Webhook (text & voice) — Phase 2
         * @description Receives Telegram Bot updates, extracts text or voice messages,
         *
         *     processes them through the multilingual AI intake pipeline,
         *     and returns a reply with the tracking ID.
         */
        post: operations["telegram_webhook_webhooks_telegram_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/whatsapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Twilio WhatsApp Webhook stub (text & voice) — Phase 2
         * @description Accepts Twilio-formatted WhatsApp webhook requests (form-encoded or JSON),
         *
         *     runs intake through the AI pipeline, and replies with a tracking ID via TwiML XML.
         */
        post: operations["whatsapp_webhook_webhooks_whatsapp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service info */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AudioUploadResponse */
        AudioUploadResponse: {
            /** Request Id */
            request_id: string;
            /** Audio Url */
            audio_url: string;
            /** Status */
            status: string;
        };
        /** AuditLogEntry */
        AuditLogEntry: {
            /** Id */
            id: number;
            /** Actor Id */
            actor_id?: number | null;
            /** Action */
            action: string;
            /** Entity Type */
            entity_type?: string | null;
            /** Entity Id */
            entity_id?: number | null;
            /** Before Value */
            before_value?: Record<string, never> | null;
            /** After Value */
            after_value?: Record<string, never> | null;
            /** Created At */
            created_at?: string | null;
        };
        /** AuditLogListResponse */
        AuditLogListResponse: {
            /** Items */
            items: components["schemas"]["AuditLogEntry"][];
            /** Total */
            total: number;
        };
        /** Body_upload_audio_requests__request_id__audio_post */
        Body_upload_audio_requests__request_id__audio_post: {
            /**
             * Audio
             * Format: binary
             */
            audio: string;
        };
        /** ClusterCorrection */
        ClusterCorrection: {
            /** Issue Type */
            issue_type?: string | null;
            /** Location Notes */
            location_notes?: string | null;
            /** Note */
            note: string;
        };
        /** ClusterDetail */
        ClusterDetail: {
            /** Id */
            id: number;
            /** Issue Type */
            issue_type: string;
            /** Status */
            status: string;
            /** Independent Demand Count */
            independent_demand_count: number;
            /** Raw Message Count */
            raw_message_count: number;
            /** District */
            district?: string | null;
            /** Location */
            location?: Record<string, never> | null;
            /** Review Status */
            review_status?: string | null;
            /** Uncertainty Notes */
            uncertainty_notes?: string[];
        };
        /** ClusterListResponse */
        ClusterListResponse: {
            /** Items */
            items: components["schemas"]["ClusterSummary"][];
            /** Total */
            total: number;
        };
        /** ClusterSummary */
        ClusterSummary: {
            /** Id */
            id: number;
            /** Issue Type */
            issue_type: string;
            /** Status */
            status: string;
            /** Independent Demand Count */
            independent_demand_count: number;
            /** Raw Message Count */
            raw_message_count: number;
            /** District */
            district?: string | null;
        };
        /** DatasetInfo */
        DatasetInfo: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Source Label */
            source_label: string;
            /** Version */
            version: string;
            /** Ingested At */
            ingested_at?: string | null;
        };
        /** DatasetListResponse */
        DatasetListResponse: {
            /** Items */
            items: components["schemas"]["DatasetInfo"][];
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: Record<string, never> | null;
        };
        /**
         * EvidencePanel
         * @description PRD §10.3 shape. Every number traceable to a stored field or formula (FR-052).
         */
        EvidencePanel: {
            /** Cluster Id */
            cluster_id: number;
            /** Issue Type */
            issue_type: string;
            /** Independent Demand Count */
            independent_demand_count: number;
            /** Raw Message Count */
            raw_message_count: number;
            /** Location */
            location?: Record<string, never> | null;
            /** Infrastructure Context */
            infrastructure_context?: Record<string, never> | null;
            /** Existing Project Check */
            existing_project_check?: Record<string, never> | null;
            /** Priority Factors */
            priority_factors?: Record<string, never> | null;
            /** Uncertainty Notes */
            uncertainty_notes?: string[];
            /** Dataset Versions */
            dataset_versions?: string[];
            /** Evidence Request Ids */
            evidence_request_ids?: number[];
            /** Evidence Reference Codes */
            evidence_reference_codes?: string[];
        };
        /** GapAnalysisResult */
        GapAnalysisResult: {
            /** Cluster Id */
            cluster_id: number;
            /** Gap Found */
            gap_found?: boolean | null;
            /** Demand Summary */
            demand_summary?: string | null;
            /** Gap Summary */
            gap_summary?: string | null;
            /** Recommendation Summary */
            recommendation_summary?: string | null;
            /** Benchmark Used */
            benchmark_used?: string | null;
            /** Conflicting Project */
            conflicting_project?: Record<string, never> | null;
            /** Uncertainty Notes */
            uncertainty_notes?: string[];
            /** Evidence Request Ids */
            evidence_request_ids?: number[];
            /** Evidence Reference Codes */
            evidence_reference_codes?: string[];
        };
        /** GeoJSONFeature */
        GeoJSONFeature: {
            /**
             * Type
             * @default Feature
             */
            type: string;
            /** Geometry */
            geometry?: Record<string, never> | null;
            /** Properties */
            properties?: Record<string, never>;
        };
        /** GeoJSONFeatureCollection */
        GeoJSONFeatureCollection: {
            /**
             * Type
             * @default FeatureCollection
             */
            type: string;
            /** Features */
            features?: components["schemas"]["GeoJSONFeature"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** App */
            app: string;
            /** Version */
            version: string;
            /** Env */
            env: string;
            /**
             * Database
             * @default unknown
             */
            database: string;
        };
        /** InfrastructureLayerResponse */
        InfrastructureLayerResponse: {
            /** Infrastructure */
            infrastructure?: Record<string, never>[];
            /** Demographics */
            demographics?: Record<string, never>[];
            /** Dataset Version */
            dataset_version?: string | null;
            /** Source Label */
            source_label?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Role */
            role: string;
        };
        /**
         * NotImplementedResponse
         * @description Uniform scaffold response for every unimplemented business endpoint.
         */
        NotImplementedResponse: {
            error?: components["schemas"]["ErrorBody"];
        };
        /** OutcomeResponse */
        OutcomeResponse: {
            /** Cluster Id */
            cluster_id: number;
            /** Baseline */
            baseline?: Record<string, never> | null;
            /** Followup */
            followup?: Record<string, never> | null;
            /**
             * Is Synthetic
             * @default true
             */
            is_synthetic: boolean;
            /**
             * Disclaimer
             * @default Observed change, not proven causal impact (FR-067)
             */
            disclaimer: string;
        };
        /** PriorityBreakdown */
        PriorityBreakdown: {
            /** Cluster Id */
            cluster_id: number;
            /** Demand */
            demand?: number | null;
            /** Gap */
            gap?: number | null;
            /** Impact */
            impact?: number | null;
            /** Equity Adjustment */
            equity_adjustment?: number | null;
            /** Funded Penalty */
            funded_penalty?: number | null;
            /** Weights */
            weights?: {
                [key: string]: number;
            } | null;
            /** Priority Index */
            priority_index?: number | null;
            /**
             * Is Incomplete
             * @default false
             */
            is_incomplete: boolean;
            /** Evidence Request Ids */
            evidence_request_ids?: number[];
        };
        /** RequestCreate */
        RequestCreate: {
            /** Channel */
            channel: string;
            /** Language Hint */
            language_hint?: string | null;
            /** Text */
            text?: string | null;
            /** Location Text */
            location_text?: string | null;
            /** Audio Base64 */
            audio_base64?: string | null;
            /** Consent Ack */
            consent_ack: boolean;
        };
        /** RequestCreateResponse */
        RequestCreateResponse: {
            /** Request Id */
            request_id: string;
            /** Status */
            status: string;
            /** Reference Code */
            reference_code: string;
            /** Issue Type */
            issue_type?: string | null;
            /** Location */
            location?: string | null;
        };
        /** RequestStatusResponse */
        RequestStatusResponse: {
            /** Request Id */
            request_id: string;
            /** Reference Code */
            reference_code: string;
            /** Status */
            status: string;
            /** Language */
            language?: string | null;
            /** Transcript */
            transcript?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Issue Type */
            issue_type?: string | null;
            /** Location */
            location?: string | null;
        };
        /** ReviewActionCreate */
        ReviewActionCreate: {
            /** Action */
            action: string;
            /** Note */
            note: string;
        };
        /** ReviewActionResponse */
        ReviewActionResponse: {
            /** Cluster Id */
            cluster_id: number;
            /** Action */
            action: string;
            /** Review Status */
            review_status: string;
            /** Audit Log Id */
            audit_log_id?: number | null;
        };
        /** SimulationCreate */
        SimulationCreate: {
            /**
             * Sector Allocations
             * @description Budget per sector in ₹: roads|water|health|education (FR-053)
             */
            sector_allocations: {
                [key: string]: number;
            };
        };
        /** SimulationResult */
        SimulationResult: {
            /** Scenario Id */
            scenario_id: string;
            /** Sector Allocations */
            sector_allocations: {
                [key: string]: number;
            };
            /** Coverable Clusters Before */
            coverable_clusters_before?: number | null;
            /** Coverable Clusters After */
            coverable_clusters_after?: number | null;
            /**
             * Disclaimer
             * @default Estimates use synthetic/curated cost data — not official budget figures (FR-056)
             */
            disclaimer: string;
        };
        /** TelegramWebhookResponse */
        TelegramWebhookResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Method
             * @default sendMessage
             */
            method: string;
            /** Chat Id */
            chat_id?: number | null;
            /** Text */
            text: string;
            /** Request Id */
            request_id: string;
            /** Reference Code */
            reference_code: string;
            /** Status */
            status: string;
            /** Issue Type */
            issue_type: string;
            /** Location */
            location?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionResponse */
        VersionResponse: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /**
             * Api Version
             * @default v1
             */
            api_version: string;
            /**
             * Scaffold
             * @default true
             */
            scaffold: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotImplementedResponse"];
                };
            };
        };
    };
    upload_audio_requests__request_id__audio_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_audio_requests__request_id__audio_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_request_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clusters_clusters_get: {
        parameters: {
            query?: {
                sector?: string | null;
                issue_type?: string | null;
                district?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cluster_clusters__cluster_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cluster_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_cluster_clusters__cluster_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cluster_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClusterCorrection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_cluster_clusters__cluster_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cluster_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewActionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_clusters__cluster_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cluster_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePanel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gap_analysis_clusters__cluster_id__gap_analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cluster_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapAnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_priority_clusters__cluster_id__priority_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cluster_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriorityBreakdown"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cluster_geojson_geospatial_clusters_get: {
        parameters: {
            query?: {
                sector?: string | null;
                district?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoJSONFeatureCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    infrastructure_layer_infrastructure_get: {
        parameters: {
            query?: {
                asset_type?: string | null;
                district?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfrastructureLayerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_simulation_simulations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_outcome_clusters__cluster_id__outcome_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cluster_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetListResponse"];
                };
            };
        };
    };
    list_audit_logs_audit_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogListResponse"];
                };
            };
        };
    };
    telegram_webhook_webhooks_telegram_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramWebhookResponse"];
                };
            };
        };
    };
    whatsapp_webhook_webhooks_whatsapp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
}

/* ---------------------------------------------------------------- errors */

export interface ErrorBody {
  code: string;
  message: string;
  details?: Record<string, unknown> | null;
}

export interface ErrorEnvelope {
  error: ErrorBody;
}

/* ---------------------------------------------------------------- auth */

export type Role = "citizen" | "analyst" | "reviewer" | "decision_maker" | "admin";

export interface LoginResponse {
  access_token: string;
  token_type: string;
  role: Role;
}

/* ---------------------------------------------------------------- requests */

export type Channel = "text" | "voice";
export type LanguageHint = "hi" | "mr" | "en";

export interface RequestCreate {
  channel: Channel;
  language_hint?: LanguageHint | null;
  text?: string;
  location_text?: string;
  audio_base64?: string;
  consent_ack: true; // FR-005: literally must be true
}

export interface RequestCreateResponse {
  request_id: string;
  status: string;
  reference_code: string;
}

export interface RequestStatusResponse {
  request_id: string;
  reference_code: string;
  status: string;
  language?: string | null;
  transcript?: string | null;
  created_at?: string | null;
}

/* ---------------------------------------------------------------- clusters */

export type ClusterStatus =
  | "forming"
  | "active"
  | "under_review"
  | "approved"
  | "rejected"
  | "archived"; // FR-022 lifecycle

export interface ClusterSummary {
  id: number;
  issue_type: string;
  status: ClusterStatus;
  independent_demand_count: number; // FR-024: always shown alongside raw count
  raw_message_count: number;
  district?: string | null;
  village_ward?: string | null;
  priority_score?: number | null;
}

export interface ClusterDetail extends ClusterSummary {
  location?: Record<string, unknown> | null;
  review_status?: string | null;
  uncertainty_notes: string[];
}

export interface ClusterListResponse {
  items: ClusterSummary[];
  total: number;
}

/* ---------------------------------------------------------------- review */

export type ReviewActionType = "approve" | "reject" | "request_more_evidence"; // FR-059

export interface ReviewActionCreate {
  action: ReviewActionType;
  note: string; // required
}

export interface ReviewActionResponse {
  cluster_id: number;
  action: ReviewActionType;
  review_status: string;
  audit_log_id?: number | null;
}

export interface ClusterCorrection {
  issue_type?: string;
  location_notes?: string;
  note: string;
}

/* ---------------------------------------------------------------- evidence */

export interface EvidencePanel {
  cluster_id: number;
  issue_type: string;
  independent_demand_count: number;
  raw_message_count: number;
  location?: Record<string, unknown> | null;
  infrastructure_context?: Record<string, unknown> | null;
  existing_project_check?: Record<string, unknown> | null;
  priority_factors?: Record<string, unknown> | null;
  uncertainty_notes: string[];
  dataset_versions: string[];
  evidence_request_ids?: number[];
  evidence_reference_codes?: string[];
}

export interface GapAnalysisResult {
  cluster_id: number;
  gap_found?: boolean | null;
  demand_summary?: string | null; // FR-044: three separate labelled fields
  gap_summary?: string | null;
  recommendation_summary?: string | null;
  benchmark_used?: string | null;
  conflicting_project?: Record<string, unknown> | null;
  uncertainty_notes: string[];
  evidence_request_ids?: number[];
  evidence_reference_codes?: string[];
}

export interface PriorityBreakdown {
  cluster_id: number;
  demand?: number | null;
  gap?: number | null;
  impact?: number | null;
  equity_adjustment?: number | null;
  funded_penalty?: number | null;
  weights?: Record<string, number> | null;
  priority_index?: number | null;
  is_incomplete: boolean; // FR-048
  evidence_request_ids?: number[];
}

/* ---------------------------------------------------------------- geo / infra */

export interface GeoJSONFeature {
  type: "Feature";
  geometry: Record<string, unknown> | null; // null → needs-geocoding list (FR-033)
  properties: Record<string, unknown>;
}

export interface GeoJSONFeatureCollection {
  type: "FeatureCollection";
  features: GeoJSONFeature[];
}

export interface InfrastructureLayerResponse {
  infrastructure: Record<string, unknown>[];
  demographics: Record<string, unknown>[];
  dataset_version?: string | null;
  source_label?: "confirmed" | "candidate" | "synthetic" | null; // FR-057
}

/* ---------------------------------------------------------------- simulation */

export interface SimulationCreate {
  sector_allocations: Partial<Record<"roads" | "water" | "health" | "education", number>>; // FR-053
}

export interface SimulationResult {
  scenario_id: string;
  sector_allocations: Record<string, number>;
  coverable_clusters_before?: number | null;
  coverable_clusters_after?: number | null;
  disclaimer: string; // FR-056
}

/* ---------------------------------------------------------------- outcome */

export interface OutcomeResponse {
  cluster_id: number;
  baseline?: Record<string, unknown> | null;
  followup?: Record<string, unknown> | null;
  is_synthetic: boolean; // FR-057
  disclaimer: string; // FR-067
}

/* ---------------------------------------------------------------- datasets/audit */

export interface DatasetInfo {
  id: number;
  name: string;
  source_label: "confirmed" | "candidate" | "synthetic";
  version: string;
  ingested_at?: string | null;
}

export interface DatasetListResponse {
  items: DatasetInfo[];
}

export interface AuditLogEntry {
  id: number;
  actor_id?: number | null;
  action: string;
  entity_type?: string | null;
  entity_id?: number | null;
  before_value?: Record<string, unknown> | null;
  after_value?: Record<string, unknown> | null;
  created_at?: string | null;
}

export interface AuditLogListResponse {
  items: AuditLogEntry[];
  total: number;
}
