"""Add user_id to requests

Revision ID: b2b2de153a7c
Revises: 14a5125fb462
Create Date: 2026-09-30 21:57:07.594489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'b2b2de153a7c'
down_revision = '14a5125fb462'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen_requests', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_citizen_requests_user_id'), 'citizen_requests', ['user_id'], unique=False)
    op.create_foreign_key(None, 'citizen_requests', 'users', ['user_id'], ['id'])
    
    op.add_column('extracted_entities', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_extracted_entities_user_id'), 'extracted_entities', ['user_id'], unique=False)
    op.create_foreign_key(None, 'extracted_entities', 'users', ['user_id'], ['id'])
    
    op.add_column('request_transcriptions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_request_transcriptions_user_id'), 'request_transcriptions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'request_transcriptions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
