import type {
  ClusterSummary,
  ClusterDetail,
  GeoJSONFeature,
  EvidencePanel,
  GapAnalysisResult,
  PriorityBreakdown,
} from "@/types/api";

export const MOCK_CLUSTERS: (ClusterDetail & { lat: number; lng: number; country: string })[] = [
  {
    id: 1,
    issue_type: "water_supply_deficit",
    status: "active",
    independent_demand_count: 342,
    raw_message_count: 489,
    district: "Chhatrapati Sambhajinagar",
    village_ward: "Paithan Rural Hub",
    priority_score: 84.5,
    country: "india",
    lat: 19.482,
    lng: 75.385,
    uncertainty_notes: [
      "High seasonal variance during pre-monsoon months",
      "94.2% semantic convergence across Marathi & Hindi voice reports",
      "Zero astroturfed coordinate repetition detected",
    ],
    review_status: "pending_review",
    location: {
      type: "Point",
      coordinates: [75.385, 19.482],
      district: "Chhatrapati Sambhajinagar",
      state: "Maharashtra",
      country: "India",
    },
  },
  {
    id: 2,
    issue_type: "drainage_flood_hazard",
    status: "active",
    independent_demand_count: 289,
    raw_message_count: 412,
    district: "Zona Norte",
    village_ward: "Favela da Maré, Rio de Janeiro",
    priority_score: 88.0,
    country: "brazil",
    lat: -22.859,
    lng: -43.245,
    uncertainty_notes: [
      "Open canal overflow risk directly threatens 1,400 households",
      "Portuguese audio transcripts corroborate severe drainage blockage",
      "High social vulnerability index (SVI 0.82)",
    ],
    review_status: "flagged_urgent",
    location: {
      type: "Point",
      coordinates: [-43.245, -22.859],
      district: "Zona Norte",
      state: "Rio de Janeiro",
      country: "Brazil",
    },
  },
  {
    id: 3,
    issue_type: "electrical_grid_failure",
    status: "forming",
    independent_demand_count: 215,
    raw_message_count: 360,
    district: "Region D",
    village_ward: "Soweto Ward 42, Johannesburg",
    priority_score: 82.3,
    country: "south_africa",
    lat: -26.248,
    lng: 27.854,
    uncertainty_notes: [
      "Repeated transformer explosions impacting local maternity clinic",
      "Corroborated by WhatsApp text intake and voice call submissions",
      "Overload frequency 3.8x above municipal maintenance threshold",
    ],
    review_status: "pending_review",
    location: {
      type: "Point",
      coordinates: [27.854, -26.248],
      district: "Region D",
      state: "Gauteng",
      country: "South Africa",
    },
  },
  {
    id: 4,
    issue_type: "primary_healthcare_deficit",
    status: "active",
    independent_demand_count: 178,
    raw_message_count: 230,
    district: "Pune Rural",
    village_ward: "Shirur Rural Ward",
    priority_score: 78.2,
    country: "india",
    lat: 18.825,
    lng: 74.378,
    uncertainty_notes: [
      "Travel distance to nearest functioning PHC exceeds 18km",
      "High concentration of maternal healthcare requests",
    ],
    review_status: "approved",
    location: {
      type: "Point",
      coordinates: [74.378, 18.825],
      district: "Pune Rural",
      state: "Maharashtra",
      country: "India",
    },
  },
  {
    id: 5,
    issue_type: "hillside_retention_risk",
    status: "under_review",
    independent_demand_count: 145,
    raw_message_count: 198,
    district: "Morros",
    village_ward: "Santos Encosta",
    priority_score: 75.6,
    country: "brazil",
    lat: -23.953,
    lng: -46.331,
    uncertainty_notes: [
      "Geotechnical landslide susceptibility rating level 4",
      "Historical rainfall triggers structural earth movement",
    ],
    review_status: "under_review",
    location: {
      type: "Point",
      coordinates: [-46.331, -23.953],
      district: "Morros",
      state: "São Paulo",
      country: "Brazil",
    },
  },
  {
    id: 6,
    issue_type: "sanitation_wastewater_deficit",
    status: "active",
    independent_demand_count: 264,
    raw_message_count: 388,
    district: "City of Cape Town",
    village_ward: "Khayelitsha Site C",
    priority_score: 79.1,
    country: "south_africa",
    lat: -34.037,
    lng: 18.665,
    uncertainty_notes: [
      "Communal ablution facility ratio 1:85 households (target 1:25)",
      "High prevalence of waterborne illness reporting",
    ],
    review_status: "pending_review",
    location: {
      type: "Point",
      coordinates: [18.665, -34.037],
      district: "City of Cape Town",
      state: "Western Cape",
      country: "South Africa",
    },
  },
  {
    id: 7,
    issue_type: "water_supply_deficit",
    status: "active",
    independent_demand_count: 278,
    raw_message_count: 395,
    district: "Region D",
    village_ward: "Protea South Settlement, Soweto",
    priority_score: 86.4,
    country: "south_africa",
    lat: -26.275,
    lng: 27.852,
    uncertainty_notes: [
      "Intermittent municipal water deliveries leaving households without regular tap access",
      "91.4% semantic agreement across Zulu and Sesotho voice notes",
    ],
    review_status: "pending_review",
    location: {
      type: "Point",
      coordinates: [27.852, -26.275],
      district: "Region D",
      state: "Gauteng",
      country: "South Africa",
    },
  },
  {
    id: 8,
    issue_type: "drainage_flood_hazard",
    status: "active",
    independent_demand_count: 194,
    raw_message_count: 260,
    district: "Region D",
    village_ward: "Senaoane & Dube Basin, Soweto",
    priority_score: 81.0,
    country: "south_africa",
    lat: -26.262,
    lng: 27.870,
    uncertainty_notes: [
      "Stormwater culvert blockage causing road flooding near local transit depot",
      "High seasonal risk during convective summer rainfall",
    ],
    review_status: "pending_review",
    location: {
      type: "Point",
      coordinates: [27.870, -26.262],
      district: "Region D",
      state: "Gauteng",
      country: "South Africa",
    },
  },
  {
    id: 9,
    issue_type: "primary_healthcare_deficit",
    status: "active",
    independent_demand_count: 165,
    raw_message_count: 210,
    district: "Region G",
    village_ward: "Lenasia South Extension, Johannesburg",
    priority_score: 77.8,
    country: "south_africa",
    lat: -26.310,
    lng: 27.842,
    uncertainty_notes: [
      "Excessive transit distance (>45 mins) to nearest secondary clinic",
      "Corroborated by high elderly citizen voice intake volume",
    ],
    review_status: "approved",
    location: {
      type: "Point",
      coordinates: [27.842, -26.310],
      district: "Region G",
      state: "Gauteng",
      country: "South Africa",
    },
  },
];

export const MOCK_GEOJSON_FEATURES: GeoJSONFeature[] = MOCK_CLUSTERS.map((c) => ({
  type: "Feature",
  geometry: {
    type: "Point",
    coordinates: [c.lng, c.lat],
  },
  properties: {
    id: c.id,
    cluster_id: c.id,
    issue_type: c.issue_type,
    status: c.status,
    independent_demand_count: c.independent_demand_count,
    raw_message_count: c.raw_message_count,
    district: c.district,
    village_ward: c.village_ward,
    priority_score: c.priority_score,
    country: c.country,
    radius_meters: 650,
  },
}));

export const MOCK_INFRASTRUCTURE = [
  {
    id: "infra_01",
    name: "Paithan Main Water Treatment Plant",
    type: "water_facility",
    status: "critical_overload",
    capacity_pct: 142,
    lat: 19.475,
    lng: 75.39,
    district: "Chhatrapati Sambhajinagar",
  },
  {
    id: "infra_02",
    name: "Maré Stormwater Retention Basin #3",
    type: "drainage",
    status: "silted_clogged",
    capacity_pct: 35,
    lat: -22.855,
    lng: -43.24,
    district: "Zona Norte",
  },
  {
    id: "infra_03",
    name: "Ward 42 11kV Feeder Substation",
    type: "power_substation",
    status: "aged_deteriorated",
    capacity_pct: 128,
    lat: -26.244,
    lng: 27.859,
    district: "Region D",
  },
  {
    id: "infra_04",
    name: "Shirur Community Health Center",
    type: "health_clinic",
    status: "operational_staff_shortage",
    capacity_pct: 88,
    lat: 18.82,
    lng: 74.37,
    district: "Pune Rural",
  },
  {
    id: "infra_05",
    name: "Protea South Municipal Water Depot",
    type: "water_facility",
    status: "operational_near_capacity",
    capacity_pct: 95,
    lat: -26.272,
    lng: 27.856,
    district: "Region D",
  },
  {
    id: "infra_06",
    name: "Lenasia South Community Health Center",
    type: "health_clinic",
    status: "overloaded",
    capacity_pct: 135,
    lat: -26.308,
    lng: 27.845,
    district: "Region G",
  },
];

export const MOCK_PRIORITY_BREAKDOWN: Record<number, PriorityBreakdown> = {
  1: {
    cluster_id: 1,
    demand: 32.4,
    gap: 24.8,
    impact: 18.5,
    equity_adjustment: 12.8,
    funded_penalty: 4.0,
    priority_index: 84.5,
    is_incomplete: false,
    weights: {
      wd: 0.35,
      wg: 0.25,
      wi: 0.2,
      we: 0.15,
      wf: 0.05,
    },
  },
  2: {
    cluster_id: 2,
    demand: 34.0,
    gap: 26.2,
    impact: 19.1,
    equity_adjustment: 13.5,
    funded_penalty: 4.8,
    priority_index: 88.0,
    is_incomplete: false,
    weights: {
      wd: 0.35,
      wg: 0.25,
      wi: 0.2,
      we: 0.15,
      wf: 0.05,
    },
  },
};

export const MOCK_EVIDENCE_PANEL: Record<number, EvidencePanel> = {
  1: {
    cluster_id: 1,
    issue_type: "water_supply_deficit",
    independent_demand_count: 342,
    raw_message_count: 489,
    dataset_versions: ["v0.1_marathi_voice", "v0.1_pmgsy_infra"],
    evidence_reference_codes: ["CP-IND-4821", "CP-IND-1049", "CP-IND-3921"],
    uncertainty_notes: [
      "Seasonal canal drought spike corroborated across Marathi voice transcripts",
      "Zero coordinate clustering spam detected",
    ],
  },
};

export const MOCK_GAP_ANALYSIS: Record<number, GapAnalysisResult> = {
  1: {
    cluster_id: 1,
    gap_found: true,
    benchmark_used: "PMGSY & Jal Jeevan Mission 55 LPCD Habitation Standard",
    demand_summary: "342 independent requests for potable pipeline water delivery",
    gap_summary: "4.5km deficit between main canal balancing reservoir and sector 4",
    recommendation_summary: "Deploy ductile iron feeder pipeline and replacement flow valves",
    uncertainty_notes: ["Requires ground geological inspection of rocky terrain"],
  },
};
